# Generated by Django 6.0.3 on 2026-03-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
